---
title: "Sewanee Bird Observations"
output: html_document
author: 'Jillian Hall'

---
## Methods:

Bird counts and identifications were collected from nine locations on Sewanee's campus. Birds were identified through visuals or vocalizations and then recorded using a shiny data entry app. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
####################### LOAD IN PACKAGES ###################################
library(readr)
library(DT)
library(ggplot2)
library(dplyr)
library(leaflet)
library(tinytable)
######################### LOAD IN DATA ######################################

#loading in data but not using first row as names 
birds_data <- read_csv("birds_data.csv",
    col_names = FALSE)

#renaming the columns names 
birds_data<-birds_data%>%rename('building'=X4,'species'=X2)

```

```{r message=FALSE, warning=FALSE, include=FALSE}
#making a vector for buildings
building<-c('mcclurg','quintard','tennessee ave','snowden','dupont library','fitwell','beihl','mccrady','memorial cross') 

#making a vectors of the latitude of the buildings 
lat<-c(35.20322,35.19755,35.20028,35.20332,35.20472,35.20286,35.20411,35.20284,35.19232)

#making a vector of the longitude of the buildings
lng<-c(-85.92029,-85.92522,-85.92205,-85.91758,-85.91785,-85.92076,-85.92134,-85.91811,-85.93706)

#adding all these vectors to gether to make a dataframe 
locations<-data.frame(building,lat,lng)



```


```{r include=FALSE}

#grouping by building to find out how many birds were seen at each one 
total_observations<-birds_data%>%
  group_by(building)%>%
  summarise(total=n())

#grouping by building then finding the number of unique species are at each one 
number_species<-birds_data%>%
  group_by(building)%>%
  summarise(n_species=n_distinct(species))

#merging the two summaries into one data set by building 
totals<-merge(total_observations,number_species,by='building')

#then merging this new data set with the lat and lng we created earlier
totals<-merge(totals,locations,by='building')

#now making a templeate for r to paste into my map as a popup 
totals$popup_text<-paste0('Location: ', totals$building,'<br/>',
                          'Birds total: ',totals$total,'<br/>',
                          'Number of species: ',totals$n_species,'<br/>')
```
## Observations By Location

```{r echo=FALSE, message=FALSE, warning=FALSE}
#making a map and saving it as an object 
map<-totals%>%leaflet()%>%
  addTiles()%>%
  setView(lng=-85.9211,lat=35.2031,zoom=14)%>%
  addMarkers(lat=~lat,lng=~lng,popup=~popup_text)

#display map in the r markdown 
map
               
```

## Most Observed Species

```{r echo=FALSE}
speciestotal<-birds_data%>%group_by(species)%>%summarise(count=n())
tt(speciestotal%>%arrange(desc(count))%>%slice(1))

```


## Species Count 

```{r echo=FALSE, fig.height=8, fig.width=8}


ggplot(speciestotal,aes(y=species,x=count))+geom_bar(stat='identity')+labs(title='Number of Observations of Each Species')+theme_minimal()


```

## Total birds observed: 

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

tt(total_observations%>%summarise(Total_Overall=sum(total)))

```
